Online Car Rental System/Online Car Rental System/Controllers/ReportPDFController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


using Online_Car_Rental_System.Models;
using System.IO;
using System.Net.Mail;
using System.Net;
using Twilio;
using Twilio.Rest.Api.V2010.Account;
using Twilio.Types;
using System.Data;
using System.Text;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.text.html.simpleparser;
using System.Web.UI;

namespace Online_Car_Rental_System.Controllers
{
    
    public class ReportPDFController : Controller
    {

        ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            List<Car> professors = db.Cars.ToList<Car>();

            return View(professors);
        }
        public FileResult CreatePdf()
        {
            MemoryStream workStream = new MemoryStream();
            StringBuilder status = new StringBuilder("");
            DateTime dTime = DateTime.Now;
            //file name to be created 
            string strPDFFileName = string.Format("Online_Car_Rental_System_" + dTime.ToString("yyyyMMdd") + "-" + ".pdf");
            Document doc = new Document();
            doc.SetMargins(0f, 0f, 0f, 0f);
            //Create PDF Table with 5 columns
            PdfPTable tableLayout = new PdfPTable(6);
            doc.SetMargins(0f, 0f, 0f, 0f);
            //Create PDF Table

            //file will created in this path
            string strAttachment = Server.MapPath("~/Downloadss/" + strPDFFileName);


            PdfWriter.GetInstance(doc, workStream).CloseStream = false;
            doc.Open();

            //Add Content to PDF 
            doc.Add(Add_Content_To_PDF(tableLayout));

            // Closing the document
            doc.Close();

            byte[] byteInfo = workStream.ToArray();
            workStream.Write(byteInfo, 0, byteInfo.Length);
            workStream.Position = 0;


            return File(workStream, "application/pdf", strPDFFileName);

        }
        protected PdfPTable Add_Content_To_PDF(PdfPTable tableLayout)
        {

            float[] headers = { 25, 20, 20, 20, 20, 20 };  //Header Widths
            tableLayout.SetWidths(headers);        //Set the pdf headers
            tableLayout.WidthPercentage = 100;       //Set the PDF File witdh percentage
            tableLayout.HeaderRows = 1;
            //Add Title to the PDF file at the top

            List<Car> employees = db.Cars.ToList<Car>();



            tableLayout.AddCell(new PdfPCell(new Phrase("Cars Report Data", new Font(Font.FontFamily.HELVETICA, 8, 1, new iTextSharp.text.BaseColor(0, 0, 0)))) { Colspan = 12, Border = 0, PaddingBottom = 5, HorizontalAlignment = Element.ALIGN_CENTER });


            ////Add header
            AddCellToHeader(tableLayout, "name");
            AddCellToHeader(tableLayout, "Model");
            AddCellToHeader(tableLayout, "Type");
            AddCellToHeader(tableLayout, "numOfChairs");
            AddCellToHeader(tableLayout, "rentAmount");
            AddCellToHeader(tableLayout, "Color");

            ////Add body



            var x = db.Cars.ToList();
            foreach (var prof in x)
            {
                AddCellToBody(tableLayout, prof.Name.ToString());
                AddCellToBody(tableLayout, prof.Model.ToString());
                AddCellToBody(tableLayout, prof.Type.ToString());
                AddCellToBody(tableLayout, prof.numOfChairs.ToString());
                AddCellToBody(tableLayout, prof.rentAmount.ToString());
                AddCellToBody(tableLayout, prof.Color.ToString());
            }

            return tableLayout;
        }


        private static void AddCellToHeader(PdfPTable tableLayout, string cellText)
        {

            tableLayout.AddCell(new PdfPCell(new Phrase(cellText, new Font(Font.FontFamily.HELVETICA, 8, 1, iTextSharp.text.BaseColor.YELLOW))) { HorizontalAlignment = Element.ALIGN_LEFT, Padding = 5, BackgroundColor = new iTextSharp.text.BaseColor(128, 0, 0) });
        }

        private static void AddCellToBody(PdfPTable tableLayout, string cellText)
        {
            tableLayout.AddCell(new PdfPCell(new Phrase(cellText, new Font(Font.FontFamily.HELVETICA, 8, 1, iTextSharp.text.BaseColor.BLACK))) { HorizontalAlignment = Element.ALIGN_LEFT, Padding = 5, BackgroundColor = new iTextSharp.text.BaseColor(255, 255, 255) });
        }
    }
}

Online Car Rental System/Online Car Rental System/Views/ReportPDF/Index.cshtml
@model IEnumerable<Online_Car_Rental_System.Models.Car>
@{
    ViewBag.Title = "Index";
}

<br /> <br /> <br /> <br /> <br />
<div class="row">
    <div class="col-md-12">
        <div class="h2 text-center">Employee Details</div>
        <table class="table table-bordered">

            <thead>
                <tr>
                    <td>
                        Name
                    </td>

                    <td>
                        Model
                    </td>
                    <td>
                        Type
                    </td>
                    <td>
                        numOfChairs
                    </td>
                    <td>
                        rentAmount
                    </td>
                    <td>
                        Color
                    </td>
                    <td>
                        ownerClient
                    </td>

                </tr>
            </thead>
            <tbody>

                @foreach (var emp in Model)
                {
                    <tr>
                        <td>@emp.Name</td>
                        <td>@emp.Model</td>
                        <td>@emp.Type</td>
                        <td>@emp.numOfChairs</td>
                        <td>@emp.rentAmount</td>
                        <td>@emp.Color</td>
                        <td>@emp.ownerClient</td>
                    </tr>
                }
            </tbody>

        </table>

    </div>
    <div class="col-sm-2">
        <div class="btn btn-danger">@Html.ActionLink("Create Pdf", "CreatePdf", "ReportPDF") </div>

    </div>
</div>